name: 'Kexa-Action'
description: "It's Kexa version for a GitHub Action"
author: '4urcloud | Esteban MATHIA'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node16
  main: dist/index.js
