name: 'Kexa Action'
description: "It's Kexa version for a GitHub Action wrapped in Docker"
author: '4urcloud | Esteban MATHIA & Adrien EPPLING'
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  envVars:
    description: 'Serialized environment variables in JSON format'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

jobs:
  run-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file with all environment variables
        run: echo "${{ inputs.envVars }}" > .env
  
      - name: Pull Docker image
        run: docker pull innovtech/kexaction:v1.0

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name kexadockeractioncontainer --env-file .env innovtech/kexaction:v1.0 sleep infinity

      - name: Copy rules into container
        run: docker cp ./rules/* kexadockeractioncontainer:/app/rules/

      - name: Copy config into container
        run: docker cp ./config/* kexadockeractioncontainer:/app/config/

      - name: Start main application inside container
        run: docker exec kexadockeractioncontainer pnpm run start:nobuild
