name: 'Kexa Action'
description: "It's Kexa version for a GitHub Action wrapped in Docker"
author: '4urcloud | Esteban MATHIA & Adrien EPPLING'
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  ENV_VARS:
    description: 'All environment variables to be set in the .env file as a JSON object'
    required: true
    default: '{}'
  KUBECONFIG:
    description: 'Kubeconfig file content'
    required: false
    default: ''
  KUBEPREFIX:
    description: 'Kube var prefix'
    required: false
    default: ''
  WORKSPACECRED:
    description: 'Workspace credentials'
    required: false
    default: ''
  WORKSPACEPREFIX:
    description: 'Workspace var prefix'
    required: false
    default: ''
  GOOGLE_APPLICATION_CREDENTIALS:
    description: 'Google application credentials'
    required: false
    default: ''
  GOOGLE_APPLICATION_CREDENTIALS_PREFIX:
    description: 'Google application credentials prefix'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file with all environment variables
      run: echo '${{ inputs.ENV_VARS }}' > .env
      shell: bash


    # # # - name: Create .env file with all environment variables
    # # #   run: |
    # # #     echo '${{ inputs.ENV_VARS }}' | sed 's/"/\\"/g' | sed 's/ /\\ /g' > .env
    # # #   shell: bash

# maybe do not escape space but only quote, and wrap in quote
# last try , {} were being removed

    # - name: Create .env file with all environment variables
    #   run: |
    #     echo '${{ inputs.ENV_VARS }}' | sed 's/"/\\"/g' > .env
    #   shell: bash
    #   # problem is that here it escape the first and last quote, so it is not a valid json anymore

 
    - name: Display the generated .env file
      run: cat .env
      shell: bash

    - name: If Kubeconfig input exists, create kubeconfig file and set exist
      id: check_kubeconfig
      run: |
        if [ -n "${{ inputs.KUBECONFIG }}" ]; then
          echo "KUBECONFIG found."
          echo "${{ inputs.KUBECONFIG }}" > kubeconfig.yaml
          echo "${{ inputs.KUBEPREFIX }}KUBECONFIG=/app/config/kubernetes.json" >> .env
          echo "${{ inputs.KUBECONFIG }}" | python -c "import yaml, json, sys; yaml_content = sys.stdin.read(); print(json.dumps(yaml.safe_load(yaml_content), indent=2))" > kubernetes.json
          chmod 700 kubernetes.json kubeconfig.yaml
        else
          echo "KUBECONFIG not found."
        fi
      shell: bash

    - name: If Workspace credentials input exists, create workspace credentials file and set exist
      id: check_workspacecred
      run: |
        if [ -n "${{ inputs.WORKSPACECRED }}" ]; then
          echo "WORKSPACECRED found."
          echo "${{ inputs.WORKSPACECRED }}" > workspace-credentials.json
          echo "${{ inputs.WORKSPACEPREFIX }}WORKSPACECRED=/app/config/workspace-credentials.json" >> .env
          chmod 700 workspace-credentials.json
        else
          echo "WORKSPACECRED not found."
        fi
      shell: bash

    - name: If Google application credentials input exists, create Google application credentials file and set exist
      id: check_google_application_credentials
      run: |
        if [ -n "${{ inputs.GOOGLE_APPLICATION_CREDENTIALS }}" ]; then
          echo "GOOGLE_APPLICATION_CREDENTIALS found."
          echo "${{ inputs.GOOGLE_APPLICATION_CREDENTIALS }}" > google-application-credentials.json
          echo "${{ inputs.GOOGLE_APPLICATION_CREDENTIALS_PREFIX }}GOOGLE_APPLICATION_CREDENTIALS=/app/config/google-application-credentials.json" >> .env
          chmod 700 google-application-credentials.json
        else
          echo "GOOGLE_APPLICATION_CREDENTIALS not found."
        fi
      shell: bash

    - name: Pull Docker image
      run: docker pull innovtech/kexaction:v1.4.2
      shell: bash

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 --name kexadockeractioncontainer --env-file .env innovtech/kexaction:v1.4.2 sleep infinity
      shell: bash
      if: ${{ success() }}

    - name: Copy kubeconfig into container
      run: |
        docker cp kubeconfig.yaml kexadockeractioncontainer:/app/
      shell: bash
      continue-on-error: true
      if: ${{ success() }}

    - name: Copy kube json into container
      run: |
        docker cp kubernetes.json kexadockeractioncontainer:/app/config/
      shell: bash
      continue-on-error: true
      if: ${{ success() }}

    # - name: Copy rules into container
    #   run: |
    #     for file in ./rules/*; do
    #       docker cp "$file" kexadockeractioncontainer:/app/rules/
    #     done
    #   shell: bash
    #   if: ${{ success() }}

    # - name: Copy config into container
    #   run: |
    #     for file in ./config/*; do
    #       docker cp "$file" kexadockeractioncontainer:/app/config/
    #     done
    #   shell: bash
    #   if: ${{ success() }}

    - name: Copy rules into container
      run: |
        docker cp ./rules kexadockeractioncontainer:/app/
      shell: bash
      if: ${{ success() }}

    - name: Copy config into container
      run: |
        docker cp ./config kexadockeractioncontainer:/app/
      shell: bash
      if: ${{ success() }}

    - name: Start main application inside container
      run: |
        docker exec kexadockeractioncontainer sh -c '
          pnpm run start:nobuild
          EXIT_CODE=$?
          echo "Exit code: $EXIT_CODE"
          if [ $EXIT_CODE -ne 0 ]; then
            echo "pnpm run start:nobuild failed with exit code $EXIT_CODE"
            exit $EXIT_CODE
          fi
        '
      shell: bash


    # delete kube config file if created
    - name: Delete kubeconfig file
      if: steps.check_kubeconfig.outputs.exists == 'true'
      run: rm kubeconfig.yaml
      continue-on-error: true
      shell: bash